### ISSUE TITLE
SG換彈

### ISSUE THREAD

**Issue by CatsSky** [ynntk4815/gf#3]
SG應計算裝填時間 並且裝填時不會觸發技能
公式參考http://bbs.ngacn.cc/read.php?tid=11580011

**Comment by ynntk4815** [comment]
855819c75c37f42aeefbb7f36567ed15e87485f3

note:只爬到有人測過100frame 沒公式

**Comment by ynntk4815** [comment]
efe19798a6efdb76f83f82c08575e6f8f4784831
